language: ruby
rvm: 2.1.1
before_install: sudo apt-get install -qq vim vim-nox vim-gtk cmake gcc clang build-essential
before_script:
  - "vim --version"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6f473fd571a127025dca
    on_success: change
    on_failure: always
    on_start: false
